// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMH0-iOebOxvflWF9vpxaEvXKZF8Qxagc',
    appId: '1:245856399647:web:8a37060a7022051306002a',
    messagingSenderId: '245856399647',
    projectId: 'flutter-task06-travel-app-beg',
    authDomain: 'flutter-task06-travel-app-beg.firebaseapp.com',
    storageBucket: 'flutter-task06-travel-app-beg.firebasestorage.app',
    measurementId: 'G-VLX66L7XJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvDTFD9beaJ6nfS3LW__P43tQoLScFDU',
    appId: '1:245856399647:android:c54accb80541e83206002a',
    messagingSenderId: '245856399647',
    projectId: 'flutter-task06-travel-app-beg',
    storageBucket: 'flutter-task06-travel-app-beg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacj3-uxksQw6gIjq7uOSrpX2LdopKbY8',
    appId: '1:245856399647:ios:8f91d38f3f32200e06002a',
    messagingSenderId: '245856399647',
    projectId: 'flutter-task06-travel-app-beg',
    storageBucket: 'flutter-task06-travel-app-beg.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask06TravelAppBeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacj3-uxksQw6gIjq7uOSrpX2LdopKbY8',
    appId: '1:245856399647:ios:8f91d38f3f32200e06002a',
    messagingSenderId: '245856399647',
    projectId: 'flutter-task06-travel-app-beg',
    storageBucket: 'flutter-task06-travel-app-beg.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask06TravelAppBeg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMH0-iOebOxvflWF9vpxaEvXKZF8Qxagc',
    appId: '1:245856399647:web:3c7aadc761f4e02f06002a',
    messagingSenderId: '245856399647',
    projectId: 'flutter-task06-travel-app-beg',
    authDomain: 'flutter-task06-travel-app-beg.firebaseapp.com',
    storageBucket: 'flutter-task06-travel-app-beg.firebasestorage.app',
    measurementId: 'G-MHBHVMVW0X',
  );
}
